### ISSUE TITLE
review ethical practices for health disparities analysis

### ISSUE THREAD

**Issue by lakikowolfe** [fredhutchio/practice-machine-learning#4]
- [On Racism: A New Standard For Publishing On Racial Health Inequities - Rhea W. Boyd Edwin G. Lindo Lachelle D. Weeks Monica R. McLemore](https://www.healthaffairs.org/do/10.1377/hblog20200630.939347/full/?utm_medium=social&utm_source=twitter&utm_campaign=blog&utm_content=Boyd&)

**Comment by k8hertweck** [comment]
Added to concepts course reading list
